services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5433:5433'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - learning
  cache:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./cache-data:/data
    networks:
      - learning

networks:
  learning:  
    driver: bridge


